default_platform(:ios)

platform :ios do

# Configurations
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

  desc "Description of what the lane does"
  lane :demo_lane do
	build_app(
		workspace: "DemoCICD.xcworkspace",
		export_method: "development",
		include_bitcode: false,
		clean: true,
		scheme: "DemoCICD",
		export_options: {
			uploadBitcode: false,
      			uploadSymbols: true, 
      			compileBitcode: false
			
		},
		output_directory: "~/Desktop/Builds/stage/"
	)
  end

end
