name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Install Dependencies
      run: |
        cd ..
        cd ..
        pod cache clean --all
        pod install
      shell: bash
    - name: execute fastlane
      run: bundle exec fastlane demo_lane
      env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
